import { useEffect, useState } from "react";

import { createReply, getReplies } from "../../api/reply.api";

interface Props {
  comment: any;
}

export default function ReviewCard({ comment }: Props) {
  const [reply, setReply] = useState("");

  const [replies, setReplies] = useState<any[]>([]);

  const [saved, setSaved] = useState(false);

  async function loadReplies() {
    const response = await getReplies(comment.id);

    setReplies(response.data);
  }

  useEffect(() => {
    loadReplies();
  }, []);

  async function handleSave() {
    if (!reply.trim()) {
      return;
    }

    await createReply({
      commentId: comment.id,
      content: reply,
    });

    setReply("");

    setSaved(true);

    await loadReplies();
  }

  return (
    <div
      className="
      bg-white
      border
      rounded-xl
      p-5
      "
    >
      {/* Customer */}

      <h3
        className="
        font-semibold
        text-lg
        "
      >
        {comment.authorName}
      </h3>

      {/* Rating */}

      {comment.rating && (
        <p
          className="
          mt-2
          text-yellow-600
          "
        >
          {"⭐".repeat(comment.rating)}
        </p>
      )}

      {/* Review */}

      <p
        className="
        mt-3
        text-gray-600
        "
      >
        {comment.content}
      </p>

      {/* Status */}

      <div
        className="
        mt-3
        "
      >
        <span className="text-gray-500">Status:</span>

        <span
          className="
          ml-2
          font-semibold
          "
        >
          {comment.reply ? "REPLIED" : comment.status}
        </span>
      </div>

      {/* Automatic AI Reply */}

      {comment.reply && (
        <div
          className="
          mt-5
          border
          rounded-lg
          p-4
          bg-gray-50
          "
        >
          <h4
            className="
            font-semibold
            "
          >
            AI Reply
          </h4>

          <p
            className="
            mt-2
            text-gray-700
            "
          >
            {comment.reply.content}
          </p>

          <p
            className="
            mt-2
            text-sm
            text-gray-500
            "
          >
            Generated by: {comment.reply.generatedBy}
          </p>
        </div>
      )}

      {/* Existing Replies */}

      <div
        className="
        mt-5
        "
      >
        <h4
          className="
          font-semibold
          "
        >
          Replies
        </h4>

        {replies.length === 0 ? (
          <p
            className="
            text-gray-400
            mt-2
            "
          >
            No replies yet
          </p>
        ) : (
          replies.map((item) => (
            <div
              key={item.id}
              className="
              mt-3
              border
              rounded-lg
              p-3
              "
            >
              <p>{item.content}</p>

              <span
                className="
                text-sm
                text-gray-500
                "
              >
                {item.status}
              </span>
            </div>
          ))
        )}
      </div>

      {/* Manual Reply */}

      <textarea
        className="
        border
        rounded-lg
        w-full
        mt-5
        p-3
        "
        placeholder="Write your reply..."
        value={reply}
        onChange={(e) => setReply(e.target.value)}
      />

      <button
        onClick={handleSave}
        className="
        mt-3
        bg-black
        text-white
        px-5
        py-2
        rounded-lg
        "
      >
        {saved ? "Saved ✓" : "Save Reply"}
      </button>
    </div>
  );
}
